In [1]:
import pandas as pd
df3=pd.read_csv('test_6.csv')

split=df3["RuleVector"].str.split("-", expand=True)
df3["count_204"]=(split=="204").sum(axis=1)

df3.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
0,HybridRV_9000,204-198-204-204-204-207-204-141,96,72,24,1.25000,2,1,28.1250,0,3,37.5,0,5
1,HybridRV_1000,238-204-136-216-156-204-238-197,52,42,10,1.19231,2,2,16.4062,0,6,75.0,0,2
2,HybridRV_5000,78-202-77-204-142-204-172-252,52,52,0,1.00000,1,3,20.3125,0,6,75.0,0,2
3,HybridRV_6000,204-204-204-172-204-204-252-136,72,72,0,1.00000,1,1,28.1250,0,3,37.5,0,5
4,HybridRV_3000,77-204-156-136-136-204-204-204,88,48,40,1.45455,2,2,18.7500,0,4,50.0,0,4

In [2]:
group_2=df3[df3["count_204"]==2]
group_2.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
1,HybridRV_1000,238-204-136-216-156-204-238-197,52,42,10,1.19231,2,2,16.4062,0,6,75.0,0,2
2,HybridRV_5000,78-202-77-204-142-204-172-252,52,52,0,1.00000,1,3,20.3125,0,6,75.0,0,2
5,HybridRV_4000,212-204-172-204-72-92-172-72,65,65,0,1.00000,1,3,25.3906,0,6,75.0,0,2
8,HybridRV_8000,77-198-192-204-156-156-192-204,68,56,12,1.17647,2,3,21.8750,0,6,75.0,0,2
11,HybridRV_1001,204-216-204-237-221-252-201-77,54,54,0,1.00000,1,2,21.0938,0,6,75.0,0,2

In [3]:
size_2=group_2.shape[0]
size_2

1939

In [ ]:
mean=group_2["NumAttractors"].mean()
minimum=group_2["NumAttractors"].min()
maximum=group_2["NumAttractors"].max()
median=group_2["NumAttractors"].median()


print("Mean:", mean)
print("Minimum:", minimum) 
print("Maximum:", maximum)
print("Median:", median)

Mean: 55.87003610108303
Minimum: 10
Maximum: 132
Median: 54.0

In [5]:
group_3=df3[df3["count_204"]==3]
group_3.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
7,HybridRV_0,142-204-204-212-132-204-207-192,66,66,0,1.00000,1,2,25.7812,0,5,62.5,0,3
9,HybridRV_7000,72-12-204-204-204-202-221-197,72,72,0,1.00000,1,2,28.1250,0,5,62.5,0,3
12,HybridRV_5001,237-202-212-108-204-204-204-141,60,44,16,1.26667,2,2,17.1875,0,5,62.5,0,3
17,HybridRV_1,204-204-252-222-72-252-238-204,60,60,0,1.00000,1,2,23.4375,0,5,62.5,0,3
21,HybridRV_1002,204-78-12-204-72-204-221-132,60,60,0,1.00000,1,2,23.4375,0,5,62.5,0,3

In [6]:
mean=group_3["NumAttractors"].mean()
minimum=group_3["NumAttractors"].min()
maximum=group_3["NumAttractors"].max()
median=group_3["NumAttractors"].median()


print("Mean:", mean)
print("Minimum:", minimum) 
print("Maximum:", maximum)
print("Median:", median)

Mean: 72.12059274399591
Minimum: 20
Maximum: 168
Median: 72.0

In [7]:
group_4=df3[df3["count_204"]==4]
group_4.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
4,HybridRV_3000,77-204-156-136-136-204-204-204,88,48,40,1.45455,2,2,18.7500,0,4,50.0,0,4
6,HybridRV_2000,204-216-204-136-204-238-204-201,92,36,56,1.60870,2,1,14.0625,0,4,50.0,0,4
10,HybridRV_9001,204-237-204-207-204-132-204-222,81,81,0,1.00000,1,1,31.6406,0,4,50.0,0,4
15,HybridRV_4001,172-204-204-238-204-141-156-204,120,104,16,1.13333,2,2,40.6250,0,4,50.0,0,4
19,HybridRV_7001,78-204-204-204-72-204-222-68,108,108,0,1.00000,1,1,42.1875,0,4,50.0,0,4

In [8]:
mean=group_4["NumAttractors"].mean()
minimum=group_4["NumAttractors"].min() 
maximum=group_4["NumAttractors"].max()
median=group_4["NumAttractors"].median()

print("Mean:", mean)
print("Minimum:", minimum) 
print("Maximum:", maximum)
print("Median:", median)

Mean: 93.01232741617358
Minimum: 24
Maximum: 192
Median: 90.0

In [9]:
group_5=df3[df3["count_204"]==5]
group_5.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
0,HybridRV_9000,204-198-204-204-204-207-204-141,96,72,24,1.25,2,1,28.1250,0,3,37.5,0,5
3,HybridRV_6000,204-204-204-172-204-204-252-136,72,72,0,1.00,1,1,28.1250,0,3,37.5,0,5
14,HybridRV_3001,204-132-204-92-237-204-204-204,108,108,0,1.00,1,3,42.1875,0,3,37.5,0,5
18,HybridRV_8001,204-221-204-204-204-132-136-204,108,108,0,1.00,1,2,42.1875,0,3,37.5,0,5
23,HybridRV_6002,204-204-78-204-204-204-142-192,120,120,0,1.00,1,1,46.8750,0,3,37.5,0,5

In [10]:
mean=group_5["NumAttractors"].mean()
minimum=group_5["NumAttractors"].min()
maximum=group_5["NumAttractors"].max() 
median=group_5["NumAttractors"].median()

print("Mean:", mean)
print("Minimum:", minimum)
print("Maximum:", maximum)
print("Median:", median)

Mean: 119.05904944791166
Minimum: 48
Maximum: 224
Median: 120.0

In [11]:
group_6=df3[df3["count_204"]==6]
group_6.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
16,HybridRV_2001,204-68-204-204-172-204-204-204,144,144,0,1.00000,1,1,56.25,0,2,25.0,0,6
20,HybridRV_9002,204-222-204-204-204-204-201-204,176,144,32,1.18182,2,1,56.25,0,2,25.0,0,6
24,HybridRV_3002,108-204-204-204-204-204-204-207,192,192,0,1.00000,1,1,75.00,0,2,25.0,0,6
26,HybridRV_2002,204-72-204-204-204-72-204-204,144,144,0,1.00000,1,1,56.25,0,2,25.0,0,6
30,HybridRV_9003,204-207-204-12-204-204-204-204,144,144,0,1.00000,1,1,56.25,0,2,25.0,0,6

In [12]:
mean=group_6["NumAttractors"].mean()
minimum=group_6["NumAttractors"].min()
maximum=group_6["NumAttractors"].max()
median=group_6["NumAttractors"].median()

print("Mean:", mean)
print("Minimum:", minimum)
print("Maximum:", maximum)
print("Median:", median)

Mean: 152.24485699949824
Minimum: 64
Maximum: 256
Median: 144.0