In [6]:
import pandas as pd
df1=pd.read_csv('test_4.csv')

split=df1["RuleVector"].str.split("-", expand=True)
df1["count_204"]=(split=="204").sum(axis=1)

df1.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
0,HybridRV_7000,154-204-204-204-225-204-204-235,96,32,64,1.66667,2,1,12.50000,0,3,37.5,0,5
1,HybridRV_1000,154-204-24-204-71-89-111-231,33,17,16,1.48485,2,5,6.64062,0,6,75.0,0,2
2,HybridRV_5000,204-204-204-204-204-6-29-204,112,80,32,1.57143,3,2,31.25000,0,2,25.0,0,6
3,HybridRV_8000,85-204-20-15-190-175-204-204,32,8,24,2.62500,4,4,3.12500,0,5,62.5,0,3
4,HybridRV_3000,165-204-204-240-204-204-105-240,64,16,48,2.50000,3,1,6.25000,0,4,50.0,0,4

In [9]:
group_2=df1[df1["count_204"]==2]
group_2.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
1,HybridRV_1000,154-204-24-204-71-89-111-231,33,17,16,1.48485,2,5,6.64062,0,6,75.0,0,2
8,HybridRV_4000,65-180-30-80-204-65-204-102,34,0,34,4.29412,6,5,0.00000,0,6,75.0,0,2
10,HybridRV_9000,204-101-154-30-189-80-204-144,31,2,29,2.87097,4,8,0.78125,0,6,75.0,0,2
11,HybridRV_1001,111-204-89-249-180-166-204-36,36,3,33,3.38889,5,5,1.17188,0,6,75.0,0,2
21,HybridRV_1002,215-204-30-9-29-204-215-111,45,11,34,1.75556,2,3,4.29688,0,6,75.0,0,2

In [17]:
size_2=group_2.shape[0]
size_2

2003

In [22]:
group_2_maca=group_2[group_2["MACA_or_not"]==1]
group_2_maca.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
114,HybridRV_3011,105-235-204-245-204-80-255-246,6,6,0,1.0,1,2,2.34375,0,6,75.0,1,2
1067,HybridRV_106,95-89-204-204-144-255-144-29,6,6,0,1.0,1,4,2.34375,0,6,75.0,1,2
2389,HybridRV_7239,29-204-204-153-150-189-210-129,6,6,0,1.0,1,9,2.34375,0,6,75.0,1,2
3098,HybridRV_4309,80-159-204-0-204-175-154-246,8,8,0,1.0,1,5,3.12500,0,6,75.0,1,2
3456,HybridRV_2345,89-195-204-240-204-255-120-226,4,4,0,1.0,1,3,1.56250,0,6,75.0,1,2

In [23]:
size_2_ismaca=group_2_maca.shape[0]
size_2_ismaca

21

In [15]:
mean=group_2["NumAttractors"].mean()
minimum=group_2["NumAttractors"].min()
maximum=group_2["NumAttractors"].max()
median=group_2["NumAttractors"].median()


print("Mean:", mean)
print("Minimum:", minimum) 
print("Maximum:", maximum)
print("Median:", median)

Mean: 28.088866699950074
Minimum: 4
Maximum: 96
Median: 25.0

In [12]:
group_3=df1[df1["count_204"]==3]
group_3.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
3,HybridRV_8000,85-204-20-15-190-175-204-204,32,8,24,2.62500,4,4,3.1250,0,5,62.5,0,3
5,HybridRV_6000,75-154-125-204-250-204-204-75,40,4,36,3.50000,4,3,1.5625,0,5,62.5,0,3
12,HybridRV_5001,89-184-180-204-95-204-150-204,72,8,64,3.61111,6,2,3.1250,0,5,62.5,0,3
13,HybridRV_8001,144-189-204-204-204-250-210-106,42,30,12,1.28571,2,3,11.7188,0,5,62.5,0,3
17,HybridRV_1,215-180-204-209-129-204-204-219,52,0,52,5.48077,6,3,0.0000,0,5,62.5,0,3

In [18]:
size_3=group_3.shape[0]
size_3

2007

In [24]:
group_3_maca=group_3[group_3["MACA_or_not"]==1]
group_3_maca.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
319,HybridRV_7032,160-106-20-111-160-204-204-204,8,8,0,1.0,1,5,3.12500,0,5,62.5,1,3
469,HybridRV_7047,184-95-204-255-169-204-204-36,18,18,0,1.0,1,3,7.03125,0,5,62.5,1,3
653,HybridRV_5066,204-204-189-150-255-184-235-204,12,12,0,1.0,1,4,4.68750,0,5,62.5,1,3
770,HybridRV_9076,111-209-245-204-204-204-36-6,24,24,0,1.0,1,4,9.37500,0,5,62.5,1,3
1115,HybridRV_6111,101-0-204-204-165-204-0-46,16,16,0,1.0,1,2,6.25000,0,5,62.5,1,3

In [25]:
size_3_ismaca=group_3_maca.shape[0]
size_3_ismaca

23

In [16]:
mean_3=group_3["NumAttractors"].mean()
minimum_3=group_3["NumAttractors"].min()   
maximum_3=group_3["NumAttractors"].max()
median_3=group_3["NumAttractors"].median()

print("Mean for count_204 == 3:", mean_3)
print("Minimum for count_204 == 3:", minimum_3)
print("Maximum for count_204 == 3:", maximum_3)
print("Median for count_204 == 3:", median_3)

Mean for count_204 == 3: 41.15695067264574
Minimum for count_204 == 3: 8
Maximum for count_204 == 3: 110
Median for count_204 == 3: 39.0

In [19]:
group_4=df1[df1["count_204"]==4]
group_4.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
4,HybridRV_3000,165-204-204-240-204-204-105-240,64,16,48,2.50000,3,1,6.25000,0,4,50.0,0,4
6,HybridRV_2000,235-204-125-204-30-204-71-204,73,5,68,1.93151,2,1,1.95312,0,4,50.0,0,4
7,HybridRV_0,235-204-9-129-204-106-204-204,68,4,64,3.35294,6,2,1.56250,0,4,50.0,0,4
15,HybridRV_6001,86-204-204-204-149-30-204-154,88,8,80,2.95455,6,2,3.12500,0,4,50.0,0,4
16,HybridRV_2001,204-204-204-85-153-129-95-204,40,8,32,1.80000,2,5,3.12500,0,4,50.0,0,4

In [26]:
size_4=group_4.shape[0]
size_4

1957

In [27]:
group_4_maca=group_4[group_4["MACA_or_not"]==1]
group_4_maca.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
62,HybridRV_5006,159-105-180-10-204-204-204-204,16,16,0,1.0,1,7,6.250,0,4,50.0,1,4
115,HybridRV_6011,204-204-166-80-255-89-204-204,24,24,0,1.0,1,3,9.375,0,4,50.0,1,4
685,HybridRV_6068,15-160-204-204-95-204-160-204,16,16,0,1.0,1,2,6.250,0,4,50.0,1,4
1060,HybridRV_9105,204-204-255-245-235-90-204-204,24,24,0,1.0,1,5,9.375,0,4,50.0,1,4
1207,HybridRV_120,153-60-204-204-204-204-149-95,24,24,0,1.0,1,2,9.375,0,4,50.0,1,4

In [28]:
size_4_ismaca=group_4_maca.shape[0]
size_4_ismaca

28

In [36]:
mean_4=group_4["NumAttractors"].mean()
minimum_4=group_4["NumAttractors"].min()   
maximum_4=group_4["NumAttractors"].max()
median_4=group_4["NumAttractors"].median()

print("Mean for count_204 == 4:", mean_4)
print("Minimum for count_204 == 4:", minimum_4)
print("Maximum for count_204 == 4:", maximum_4)
print("Median for count_204 == 4:", median_4)

Mean for count_204 == 4: 57.53755748594788
Minimum for count_204 == 4: 16
Maximum for count_204 == 4: 128
Median for count_204 == 4: 55.0

In [30]:
group_5=df1[df1["count_204"]==5]
group_5.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
0,HybridRV_7000,154-204-204-204-225-204-204-235,96,32,64,1.66667,2,1,12.50,0,3,37.5,0,5
9,HybridRV_7001,204-204-204-204-71-250-153-204,56,16,40,1.85714,3,4,6.25,0,3,37.5,0,5
27,HybridRV_2,204-204-225-204-160-204-204-225,96,32,64,1.66667,2,1,12.50,0,3,37.5,0,5
28,HybridRV_4002,204-204-153-24-204-255-204-204,96,16,80,2.33333,3,1,6.25,0,3,37.5,0,5
29,HybridRV_7003,20-204-246-204-204-204-204-30,112,48,64,1.57143,2,1,18.75,0,3,37.5,0,5

In [31]:
size_5=group_5.shape[0]
size_5

2057

In [32]:
group_5_maca=group_5[group_5["MACA_or_not"]==1]
group_5_maca.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
267,HybridRV_26,15-204-240-204-204-204-90-204,32,32,0,1.0,1,1,12.50,0,3,37.5,1,5
480,HybridRV_9047,160-204-255-204-204-0-204-204,32,32,0,1.0,1,1,12.50,0,3,37.5,1,5
1620,HybridRV_9161,15-105-60-204-204-204-204-204,32,32,0,1.0,1,3,12.50,0,3,37.5,1,5
1834,HybridRV_3183,29-204-250-204-10-204-204-204,48,48,0,1.0,1,1,18.75,0,3,37.5,1,5
1856,HybridRV_2185,204-204-204-204-95-204-180-125,32,32,0,1.0,1,2,12.50,0,3,37.5,1,5

In [33]:
size_5_ismaca=group_5_maca.shape[0]
size_5_ismaca

36

In [35]:
mean_5=group_5["NumAttractors"].mean()
minimum_5=group_5["NumAttractors"].min()   
maximum_5=group_5["NumAttractors"].max()
median_5=group_5["NumAttractors"].median()

print("Mean for count_204 == 5:", mean_5)
print("Minimum for count_204 == 5:", minimum_5)
print("Maximum for count_204 == 5:", maximum_5)
print("Median for count_204 == 5:", median_5)

Mean for count_204 == 5: 79.37092853670394
Minimum for count_204 == 5: 32
Maximum for count_204 == 5: 160
Median for count_204 == 5: 76.0

In [37]:
group_6=df1[df1["count_204"]==6]
group_6.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
2,HybridRV_5000,204-204-204-204-204-6-29-204,112,80,32,1.57143,3,2,31.25,0,2,25.0,0,6
14,HybridRV_3001,204-204-30-204-204-204-204-189,112,32,80,1.71429,2,1,12.50,0,2,25.0,0,6
26,HybridRV_2002,204-204-204-204-204-204-45-105,128,64,64,2.00000,3,2,25.00,0,2,25.0,0,6
30,HybridRV_9002,204-204-204-204-125-204-249-204,128,64,64,1.50000,2,1,25.00,0,2,25.0,0,6
33,HybridRV_8003,204-204-204-240-204-204-89-204,96,64,32,1.33333,2,1,25.00,0,2,25.0,0,6

In [38]:
size_6=group_6.shape[0]
size_6

1976

In [39]:
group_6_maca=group_6[group_6["MACA_or_not"]==1]
group_6_maca.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
397,HybridRV_39,204-204-95-204-204-204-255-204,64,64,0,1.0,1,1,25.0,0,2,25.0,1,6
524,HybridRV_3052,204-204-204-175-255-204-204-204,64,64,0,1.0,1,2,25.0,0,2,25.0,1,6
1092,HybridRV_8108,255-204-204-204-204-204-204-246,96,96,0,1.0,1,1,37.5,0,2,25.0,1,6
1413,HybridRV_5142,165-0-204-204-204-204-204-204,64,64,0,1.0,1,2,25.0,0,2,25.0,1,6
1477,HybridRV_147,204-204-204-204-204-153-235-204,96,96,0,1.0,1,2,37.5,0,2,25.0,1,6

In [40]:
size_6_ismaca=group_6_maca.shape[0]
size_6_ismaca

35

In [41]:
mean_6=group_6["NumAttractors"].mean()
minimum_6=group_6["NumAttractors"].min()   
maximum_6=group_6["NumAttractors"].max()
median_6=group_6["NumAttractors"].median()

print("Mean for count_204 == 6:", mean_6)
print("Minimum for count_204 == 6:", minimum_6)
print("Maximum for count_204 == 6:", maximum_6)
print("Median for count_204 == 6:", median_6)

Mean for count_204 == 6: 110.60323886639677
Minimum for count_204 == 6: 64
Maximum for count_204 == 6: 192
Median for count_204 == 6: 112.0