In [1]:
import pandas as pd
df2=pd.read_csv('test_5.csv')

split=df2["RuleVector"].str.split("-", expand=True)
df2["count_204"]=(split=="204").sum(axis=1)

df2.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
0,HybridRV_5000,204-158-204-204-204-204-204-124,152,120,32,1.21053,2,1,46.875,0,2,25.0,0,6
1,HybridRV_0,168-204-204-204-204-230-204-204,152,120,32,1.21053,2,1,46.875,0,2,25.0,0,6
2,HybridRV_3000,28-204-204-204-204-84-64-204,96,96,0,1.00000,1,3,37.500,0,3,37.5,0,5
3,HybridRV_7000,188-204-204-204-157-239-204-204,144,144,0,1.00000,1,2,56.250,0,3,37.5,0,5
4,HybridRV_8000,214-79-164-204-204-204-204-204,112,48,64,1.85714,3,2,18.750,0,3,37.5,0,5

In [2]:
group_2=df2[df2["count_204"]==2]
group_2.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
8,HybridRV_6000,204-93-84-104-14-199-204-164,20,0,20,3.80000,4,6,0.00000,0,6,75.0,0,2
15,HybridRV_9001,204-8-253-199-64-69-174-204,33,33,0,1.00000,1,3,12.89060,0,6,75.0,0,2
21,HybridRV_2,204-4-224-204-152-8-157-110,26,14,12,1.46154,2,3,5.46875,0,6,75.0,0,2
24,HybridRV_8002,244-104-204-138-248-204-79-203,54,26,28,1.51852,2,2,10.15620,0,6,75.0,0,2
27,HybridRV_2002,13-204-79-88-204-64-133-143,43,27,16,1.37209,2,3,10.54690,0,6,75.0,0,2

In [3]:
size_2=group_2.shape[0]
size_2

1970

In [4]:
group_2_maca=group_2[group_2["MACA_or_not"]==1]
group_2_maca.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
83,HybridRV_7008,79-174-157-248-204-93-204-4,10,10,0,1.0,1,5,3.90625,0,6,75.0,1,2
165,HybridRV_9016,79-204-234-73-79-168-174-204,14,14,0,1.0,1,5,5.46875,0,6,75.0,1,2
286,HybridRV_1028,239-204-94-214-193-173-204-253,10,10,0,1.0,1,7,3.90625,0,6,75.0,1,2
604,HybridRV_8060,254-204-4-204-233-233-8-173,11,11,0,1.0,1,4,4.29688,0,6,75.0,1,2
605,HybridRV_9060,213-234-204-204-199-93-124-14,8,8,0,1.0,1,7,3.12500,0,6,75.0,1,2

In [5]:
size_2_ismaca=group_2_maca.shape[0]
size_2_ismaca

65

In [6]:
mean=group_2["NumAttractors"].mean()
minimum=group_2["NumAttractors"].min()
maximum=group_2["NumAttractors"].max()
median=group_2["NumAttractors"].median()


print("Mean:", mean)
print("Minimum:", minimum) 
print("Maximum:", maximum)
print("Median:", median)

Mean: 33.579187817258884
Minimum: 6
Maximum: 90
Median: 32.0

In [7]:
group_3=df2[df2["count_204"]==3]
group_3.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
7,HybridRV_2000,204-208-188-204-8-74-14-204,46,13,33,2.97826,4,4,5.07812,0,5,62.5,0,3
9,HybridRV_4000,79-204-204-204-174-93-28-13,20,20,0,1.00000,1,5,7.81250,0,5,62.5,1,3
10,HybridRV_5001,148-204-128-204-233-194-188-204,57,31,26,1.45614,2,2,12.10940,0,5,62.5,0,3
17,HybridRV_2001,204-69-109-134-213-158-204-204,48,32,16,1.58333,3,12,12.50000,0,5,62.5,0,3
26,HybridRV_1002,204-204-13-88-137-230-133-204,44,34,10,1.36364,3,6,13.28120,0,5,62.5,0,3

In [8]:
size_3=group_3.shape[0]
size_3

1998

In [9]:
group_3_maca=group_3[group_3["MACA_or_not"]==1]
group_3_maca.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
9,HybridRV_4000,79-204-204-204-174-93-28-13,20,20,0,1.0,1,5,7.81250,0,5,62.5,1,3
276,HybridRV_1027,253-204-204-253-204-8-218-213,21,21,0,1.0,1,2,8.20312,0,5,62.5,1,3
654,HybridRV_8065,217-143-254-204-204-204-208-234,24,24,0,1.0,1,5,9.37500,0,5,62.5,1,3
956,HybridRV_1095,168-223-204-74-204-204-4-213,20,20,0,1.0,1,2,7.81250,0,5,62.5,1,3
1024,HybridRV_8102,143-217-204-143-204-13-204-13,19,19,0,1.0,1,2,7.42188,0,5,62.5,1,3

In [10]:
size_3_ismaca=group_3_maca.shape[0]
size_3_ismaca

56

In [11]:
mean=group_3["NumAttractors"].mean()
minimum=group_3["NumAttractors"].min()
maximum=group_3["NumAttractors"].max()
median=group_3["NumAttractors"].median()


print("Mean:", mean)
print("Minimum:", minimum) 
print("Maximum:", maximum)
print("Median:", median)

Mean: 48.3978978978979
Minimum: 8
Maximum: 124
Median: 48.0

In [12]:
group_4=df2[df2["count_204"]==4]
group_4.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
6,HybridRV_1000,224-204-234-204-133-199-204-204,56,30,26,1.78571,3,2,11.7188,0,4,50.0,0,4
11,HybridRV_1,94-204-208-224-128-204-204-204,36,36,0,1.00000,1,3,14.0625,0,4,50.0,0,4
18,HybridRV_6001,137-109-204-128-204-204-214-204,49,35,14,1.28571,2,2,13.6719,0,4,50.0,0,4
22,HybridRV_3002,73-204-84-204-239-204-204-100,96,40,56,1.58333,2,1,15.6250,0,4,50.0,0,4
23,HybridRV_7002,204-168-204-199-204-204-248-203,82,42,40,1.48780,2,1,16.4062,0,4,50.0,0,4

In [13]:
size_4=group_4.shape[0]
size_4

2077

In [14]:
group_4_maca=group_4[group_4["MACA_or_not"]==1]
group_4_maca.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
162,HybridRV_3016,204-204-8-204-174-204-239-248,34,34,0,1.0,1,2,13.2812,0,4,50.0,1,4
353,HybridRV_7035,74-223-173-204-93-204-204-204,20,20,0,1.0,1,3,7.8125,0,4,50.0,1,4
414,HybridRV_8041,157-204-79-204-204-204-193-213,48,48,0,1.0,1,2,18.7500,0,4,50.0,1,4
732,HybridRV_3073,239-204-204-204-14-204-84-230,52,52,0,1.0,1,1,20.3125,0,4,50.0,1,4
814,HybridRV_8081,79-4-44-204-204-204-174-204,40,40,0,1.0,1,2,15.6250,0,4,50.0,1,4

In [15]:
size_4_ismaca=group_4_maca.shape[0]
size_4_ismaca

64

In [16]:
mean=group_4["NumAttractors"].mean()
minimum=group_4["NumAttractors"].min()
maximum=group_4["NumAttractors"].max()
median=group_4["NumAttractors"].median()


print("Mean:", mean)
print("Minimum:", minimum) 
print("Maximum:", maximum)
print("Median:", median)

Mean: 66.27973038035628
Minimum: 16
Maximum: 156
Median: 65.0

In [18]:
group_5=df2[df2["count_204"]==5]
group_5.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
2,HybridRV_3000,28-204-204-204-204-84-64-204,96,96,0,1.00000,1,3,37.500,0,3,37.5,0,5
3,HybridRV_7000,188-204-204-204-157-239-204-204,144,144,0,1.00000,1,2,56.250,0,3,37.5,0,5
4,HybridRV_8000,214-79-164-204-204-204-204-204,112,48,64,1.85714,3,2,18.750,0,3,37.5,0,5
5,HybridRV_9000,204-204-254-204-229-204-204-254,72,72,0,1.00000,1,1,28.125,0,3,37.5,0,5
13,HybridRV_7001,204-148-254-204-204-204-204-173,56,56,0,1.00000,1,2,21.875,0,3,37.5,0,5

In [19]:
size_5=group_5.shape[0]
size_5

1932

In [20]:
group_5_maca=group_5[group_5["MACA_or_not"]==1]
group_5_maca.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
67,HybridRV_2006,204-204-233-253-204-204-204-223,56,56,0,1.0,1,2,21.8750,0,3,37.5,1,5
299,HybridRV_4029,204-204-204-204-239-173-204-93,40,40,0,1.0,1,3,15.6250,0,3,37.5,1,5
404,HybridRV_8040,79-204-110-8-204-204-204-204,64,64,0,1.0,1,2,25.0000,0,3,37.5,1,5
565,HybridRV_9056,204-204-204-204-204-253-168-128,32,32,0,1.0,1,3,12.5000,0,3,37.5,1,5
650,HybridRV_5065,223-204-74-204-204-128-204-204,50,50,0,1.0,1,1,19.5312,0,3,37.5,1,5

In [21]:
size_5_maca=group_5_maca.shape[0]
size_5_maca

49

In [22]:
mean=group_5["NumAttractors"].mean()
minimum=group_5["NumAttractors"].min()
maximum=group_5["NumAttractors"].max()
median=group_5["NumAttractors"].median()


print("Mean:", mean)
print("Minimum:", minimum) 
print("Maximum:", maximum)
print("Median:", median)

Mean: 91.02432712215321
Minimum: 32
Maximum: 192
Median: 92.0

In [23]:
group_6=df2[df2["count_204"]==6]
group_6.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
0,HybridRV_5000,204-158-204-204-204-204-204-124,152,120,32,1.21053,2,1,46.8750,0,2,25.0,0,6
1,HybridRV_0,168-204-204-204-204-230-204-204,152,120,32,1.21053,2,1,46.8750,0,2,25.0,0,6
12,HybridRV_3001,204-204-204-204-70-204-199-204,128,64,64,1.50000,2,1,25.0000,0,2,25.0,0,6
36,HybridRV_1003,69-204-204-204-204-204-204-64,96,96,0,1.00000,1,1,37.5000,0,2,25.0,0,6
41,HybridRV_4,204-79-204-204-204-204-229-204,100,100,0,1.00000,1,1,39.0625,0,2,25.0,0,6

In [24]:
size_6=group_6.shape[0]
size_6

2023

In [25]:
group_6_maca=group_6[group_6["MACA_or_not"]==1]
group_6_maca.head()

,RuleVectorID,RuleVector,NumAttractors,NumFixedPointAttractors,NumCyclicAttractors,AvgCycleLength,MaxCycleLength,MaxChainLength,PointAttractorDensity,Reversible,ImpurityCells,ImpurityPercent,MACA_or_not,count_204
199,HybridRV_4019,204-204-204-204-204-204-248-173,64,64,0,1.0,1,3,25.00,0,2,25.0,1,6
200,HybridRV_5020,223-204-204-204-93-204-204-204,80,80,0,1.0,1,1,31.25,0,2,25.0,1,6
223,HybridRV_7022,204-204-204-234-204-204-204-223,80,80,0,1.0,1,1,31.25,0,2,25.0,1,6
361,HybridRV_36,239-204-204-204-204-204-204-213,64,64,0,1.0,1,1,25.00,0,2,25.0,1,6
437,HybridRV_2043,204-204-204-204-204-204-223-218,64,64,0,1.0,1,3,25.00,0,2,25.0,1,6

In [ ]:
size_6_ismaca=group_6_maca.shape[0]
size_6_ismaca

55

In [27]:
mean=group_6["NumAttractors"].mean()
minimum=group_6["NumAttractors"].min()
maximum=group_6["NumAttractors"].max()
median=group_6["NumAttractors"].median()


print("Mean:", mean)
print("Minimum:", minimum) 
print("Maximum:", maximum)
print("Median:", median)

Mean: 125.09540286702916
Minimum: 64
Maximum: 192
Median: 128.0